export enum AuditAction {
  USER_REGISTER = 'USER_REGISTER',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
  ROUTE_CREATED = 'ROUTE_CREATED',
  SEAT_RESERVED = 'SEAT_RESERVED',
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  ACCESS_DENIED_ROLE = 'ACCESS_DENIED_ROLE',
}
