export enum AuditAction {
  // Auth Actions
  USER_REGISTER = 'USER_REGISTER',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',

  // Server Access Actions
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  ACCESS_DENIED_ROLE = 'ACCESS_DENIED_ROLE',

  // Mail Actions
  EMAIL_SENT = 'EMAIL_SENT',
  EMAIL_FAILED = 'EMAIL_FAILED',

  // User Management Actions
  USER_CREATED = 'USER_CREATED',
}
